const youtube = [
    {
        id:1,
        link:"https://www.youtube.com/embed/lcOxhH8N3Bo"
    },
    {
      id:2,
        link:"https://www.youtube.com/embed/Y0KxZz5k-RE"
    },
    {
        id:3,
        link:"https://www.youtube.com/embed/psuRGfAaju4"
    },
    {
        id:4,
        link:"https://www.youtube.com/embed/tFW2alq3FMU"
    },
    {
        id:5,
        link:"https://www.youtube.com/embed/KiNRIR8tjFc"
    },
    {
        id:6,
        link:"https://www.youtube.com/embed/6EEW-9NDM5k"
    },
    {
        id:7,
        link:"https://www.youtube.com/embed/9sd-dBMY5IU"
    },
    {
        id:8,
        link:"https://www.youtube.com/embed/MrTz5xjmso4"
    },
    {
        id:9,
        link:"https://www.youtube.com/embed/BkjnadCaosk"
    },
    {
        id:10,
        link:"https://www.youtube.com/embed/viimfQi_pUw"
    },
    {
        id:11,
        link:"https://www.youtube.com/embed/rQSmfR1_SVE"
    },
    {
        id:12,
        link:"https://www.youtube.com/embed/wRE8SW0HVvk"
    },
    {
        id:13,
        link:"https://www.youtube.com/embed/VDq_nVYvxZQ"
    }
]

export default youtube;